framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    handle_all_throwables: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    php_errors:
        log: true
    validation:
        email_validation_mode: html5
    uid:
        default_uuid_version: 7
        time_based_uuid_version: 7
