framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus: ~

        transports:
            sync: 'sync://'

        routing:
            App\Application\Command\CommandInterface: sync
            App\Application\Query\QueryInterface: sync
