name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: xdebug
        
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Create test environment
      run: |
        echo "APP_ENV=test" > .env.test
        echo "APP_SECRET=test" >> .env.test
        echo "DATABASE_URL=sqlite:///:memory:" >> .env.test
        echo "STRIPE_SECRET_KEY=test" >> .env.test
        echo "STRIPE_WEBHOOK_SECRET=test" >> .env.test
        cp .env.test .env
      
    - name: Execute tests with coverage
      run: |
        mkdir -p build/logs
        XDEBUG_MODE=coverage SYMFONY_DEPRECATIONS_HELPER=999999 ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
        
    - name: Upload coverage results to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        ./vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
